extend type Query {
  getLists: [List] @auth
  getListById (id: ID!): List @auth
  getListsByTitle (title: String!): [List] @auth
  getListsByTag (tagName: String!): [List] @auth
  getListsByDateInterval (start: String, finish: String): [List] @auth
}