extend type Query {
  getLists: [List]
  getListById (id: ID!): List
  getListsByTitle (title: String!): [List]
  getListsByTag (tagName: String!): [List]
  getListsByDateInterval (start: String, finish: String): [List]
}