extend type Query {
  getNotes: [Note] @auth
  getNoteById (id: ID!): Note @auth
  getNotesByTitle (title: String!): [Note] @auth
  getNotesByTag (tagName: String!): [Note] @auth
  getNotesByDateInterval (start: String, finish: String): [Note] @auth
}