type Query {
  # Users queries

  getUsers: [User]
  getUserById (id: ID!): User
  getUserByUsername (username: String!): User
  getUserLists (username: String!): [List]
  getUserListById (username: String!, listId: ID!): List
  getListsByTitle (username: String!, listTitle: String!): [List]
  getListsByTag (username: String!, tagName: String!): [List]
}
