directive @auth on FIELD_DEFINITION
directive @guest on FIELD_DEFINITION
directive @admin on FIELD_DEFINITION
directive @lowercase on ARGUMENT_DEFINITION | FIELD_DEFINITION

type Query {
  _: String
}

type Mutation {
  _: String
}

type Subscription {
  _: String
}

type Error {
  path: String!,
  message: String!
}

type Response {
  success: Boolean!,
  token: String,
  errors: [Error]
}

extend type Query {
  checkToken: Boolean!
}
