type Item {
  _id: ID!
  name: String!
  checked: Boolean
}

type List {
  _id: ID!
  title: String!
  items: [Item],
  tags: [Tag],
  createdAt: String!
  updatedAt: String!
}

type Note {
  _id: ID!
  title: String
  content: String
  createdAt: String!
  updatedAt: String!
}

enum MovementType {
  deposit
  withdrawal
}

type Movement {
  _id: ID!
  type: MovementType!
  amount: Float!
  date: String!
}

type Wallet {
  _id: ID!
  name: String!
  description: String
  balance: Float
  movements: [Movement]
}

enum Sex {
  M
  F
}

enum UserType {
  premium
  admin
  standard
}

type User {
  _id: ID!
  username: String!
  email: String!
  firstName: String!
  lastName: String!
  birthDate: String!
  sex: Sex!
  notes: [Note]
  lists: [List]
  type: UserType!
  wallets: [Wallet]
  interests: [Interest]
  createdAt: String!
  updatedAt: String!
}