enum UserType {
  premium
  admin
  standard
}

type User {
  _id: ID!
  username: String!
  email: String!
  firstName: String!
  lastName: String!
  birthDate: String!
  sex: String!
  notes: [Note]
  lists: [List]
  type: UserType!
  wallets: [Wallet]
  interests: [Interest]
  createdAt: String!
  updatedAt: String!
}